### ISSUE TITLE
Implement Minimum Functionality for Service Validity Check

### ISSUE THREAD

**Issue by Syu-fu** [Syu-fu/Maushold#3]
## Task

Implement the minimum functionality required to check the service's validity.

## Subtasks

- [x] Create a list feature.
- [x] Create an API to support the list feature.
- [x] Add authentication to the pages.
